version: "3"

services:
  client:
    restart: always
    build: "./client"
    depends_on:
      - backend

  backend:
    restart: always
    build: "./backend"
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      CLIENT_URL: "https://nginx/"
      PORT: 5000
      NODE_ENV: "production"

  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "4433:4433"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/nginx.key:/etc/ssl/private/nginx.key
      - ./nginx/ssl/nginx.crt:/etc/ssl/certs/nginx.crt
    depends_on:
      - client
      - backend
