version: '3'

services:
  client:
      build: './client'
      ports:
        - '3000:3000'
      depends_on:
        - api
      environment:
        API_URL: 'http://api/api'
        SOCKET_CLIENT_URL: 'http://api/api'
  
  api:
    build: './backend'
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      ACCESS_TOKEN_SECRET: 'ala ma kota'
      REFRESH_TOKEN_SECRET: 'atok am ala'
      MONGO_HOST: 'db' 
      MONGO_PORT: 27017 
      MONGO_DATABASE: 'chess-masters'
      CLIENT_URL: 'http://127.0.0.1'
      PORT: '5000'

  db:
    image: mongo:latest
    volumes:
        - type: bind
          source: /etc/chess-masters-db
          target: /data/db
  
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - api
