version: "3"

services:
  client:
    restart: always
    build: "./client"
    depends_on:
      - backend

  backend:
    restart: always
    build: "./backend"
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      CLIENT_URL: "http://nginx/"
      PORT: 5000

  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "85:85"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - backend